[package]
name = "cellar-core"
version = "0.1.0"
authors = ["Tyr Chen <tyr.chen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11"
blake2s_simd = "0.5"
c2-chacha = "0.2"
rand = "0.7"
rust-argon2 = "0.6"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
criterion = "0.3"
quickcheck = "0.9"
quickcheck_macros = "0.8"


[[bench]]
name = "bench_cellar"
harness = false
