[package]
name = "cellar"
version = "0.1.0"
authors = ["Tyr Chen <tyr.chen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
cellar-core = { path = "../cellar-core" }
dialoguer = "0.5"
dirs = "2"
structopt = "0.3"
toml = "0.5"
tokio = { version = "0.2", features = ["fs", "io-util"] }
